# Generated by Django 4.2.17 on 2025-01-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
